# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fSIrhCApRmQxkkG6SGiZoetqjRpwKJQt

#1.Imports
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""#2.Leitura do arquivo"""

base_dados = pd.read_csv('gasolina.csv')
base_dados.head(5)

plt.title('Vendas por dia')
plt.grid(which='both', alpha=0.3)
sns.set_style()
sns.lineplot(data=base_dados, x= 'dia', y = 'venda');

plt.savefig('gasolina.png')

base_dados.info()

"""#3.Análise dos dados

###Gráfico de barras
"""

plt.figure(figsize = (11,5))
plt.grid(which='both', alpha=0.5)
plt.title('')

plt.bar(

	base_dados['dia'],
	base_dados['venda'],
	color='orange'
);